### ISSUE TITLE
Gettign error  while using mailinator api connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by anoopsingh** [ainformatico/mailinator#10]
Hi,

I am using mailinator api to get access to mailinator inbox and mail so that i can use it for my tests.
BUt i m getting below error while calling the api 👍 
connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)

Below is the code snippet i am using for it 👍 

require 'mailinator'

Mailinator.configure do |config|
  config.token = 'token key'
end
email = Mailinator::Email.get('xggddgaysingh')
puts(email.subject)

Thanks,
Anoop

**Comment by ainformatico** [comment]
Hi @anoopsingh, thanks for reporting the issue.
I believe this issue is not related to _mailinator gem_ but to your SSL setup. A quick search in google for `OpenSSL::SSL::SSLError ruby` can help you with the issue depending your operating system and configuration.
