### ISSUE TITLE
Any plan to update rubygems.org with subject change

### ISSUE THREAD

**Issue by patrick-zhang** [ainformatico/mailinator#7]
Seems the gem 0.0.3 was updated in Feb 2015, retrieve email subject commit was added in March 2015. Any plan to update rubygems.org so we can check email subject?

Thanks,
Patrick

**Comment by ainformatico** [comment]
@patrick-zhang currently there are no plans for doing so. Any Pull Request would be really welcome! 😸 
Would you be willing to provide such feature?

**Comment by t898061patrickzhang** [comment]
@ainformatico Not sure if we need Pull Request as the codes are already in master branch. It's more about re-create the gem file and upload the gemfile to rubygems.org. :)

**Comment by ainformatico** [comment]
Just bumped v0.0.4.
