### ISSUE TITLE
transform_data in models/email.rb failingcd

### ISSUE THREAD

**Issue by liapretorius** [ainformatico/mailinator#9]
transform_data failing returning nil, failing on two counts.
1. retrieve_body_html 'parts' index number to retrieve human readable text in email body should be set to 0 instead of 1. 
2. transform_data returning returns nil as written with multiple key/value assignments. It does return data when only one key/value assignment is specified.

I tried submitting a branch with the index fix but permission was denied.

module Mailinator
  module Models
    class Email < Base
      def transform_data
        {
          id: @data['data']['id'],
          subject: @data['data']['subject'],
          body: @data['data']['parts'].first['body'],
          body_html: retrieve_body_html,
          inbox_fetches_left: @data['apiInboxFetchesLeft'],
          email_fetches_left: @data['apiEmailFetchesLeft'],
          forwards_left: @data['forwardsLeft'],
          sender: @data['data']['headers']['sender'],
          from: @data['data']['from'],
          date: DateTime.parse(@data['data']['headers']['date']),
          time: @data['data']['time'],
          ip: @data['data']['ip'],
          to: @data['data']['headers']['to'],
          reply_to: @data['data']['headers']['reply-to'],
          received: @data['data']['headers']['received'],
          read?: @data['data']['been_read']
        }
      end

```
  private

  def retrieve_body_html
    html = @data['data']['parts'][1] || {}
    html['body']
  end
end
```

  end
end

**Comment by ainformatico** [comment]
Hi @liapretorius, thanks for reporting the issue. It would be really nice if you can provide a pull request with the suggested changes, unfortunately you can't create a branch in this project. The best option is to create a fork, push your changes to your fork and then open a pull request pointing to this repository.
Thanks!
